url: https://sparkandgritt.com
baseurl: /

# Site settings
title: Spark and Gritt
email: admin@sagdigi.com
description: "Adapt to Changing Business Needs"

#About Us header
aboutus:
  header: "Tech it up!"
  lead-title: "Adapt to Changing Business Needs"

# Team names, titles and social links
people:
- name: Archana Notpie
  pic: av
  position: VP, Program Management Practice
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Mithun Sharma
  pic: mg
  position: CEO
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: github
    url: http://github.com/sagdigi

# Postal address (add as many lines as necessary)
address:
  - line: San Francisco
  - line: California

# Build settings
markdown: kramdown
permalink: pretty
